#!/usr/bin/env python3
"""
convert_questions.py
====================
Reads questions from `questions.xlsx` and generates `js/questions.js`.

Usage:
    python3 convert_questions.py

The Excel file must have a sheet named "Questions" with the following columns:
    id          | unit      | topic   | question
    option_a    | option_b  | option_c | option_d
    correct     | explanation

  - `correct` is a 0-based integer: 0=A, 1=B, 2=C, 3=D
  - Rows with an empty `question` cell are skipped.

Run this script whenever you update questions.xlsx, then commit both files.
GitHub Actions will run this automatically when questions.xlsx is pushed.
"""

import sys
import json
import re
import os
from datetime import datetime, timezone

try:
    import openpyxl
except ImportError:
    print("ERROR: openpyxl is not installed. Run: pip install openpyxl", file=sys.stderr)
    sys.exit(1)

EXCEL_FILE   = os.path.join(os.path.dirname(__file__), "questions.xlsx")
OUTPUT_FILE  = os.path.join(os.path.dirname(__file__), "js", "questions.js")
SHEET_NAME   = "Questions"
REQUIRED_COLS = ["id", "unit", "topic", "question",
                 "option_a", "option_b", "option_c", "option_d",
                 "correct", "explanation"]


def load_questions(path: str) -> list[dict]:
    wb = openpyxl.load_workbook(path, data_only=True)
    if SHEET_NAME not in wb.sheetnames:
        raise ValueError(
            f"Sheet '{SHEET_NAME}' not found in {path}. "
            f"Available sheets: {wb.sheetnames}"
        )
    ws = wb[SHEET_NAME]

    # Read header row
    headers = []
    for cell in next(ws.iter_rows(min_row=1, max_row=1)):
        val = cell.value
        headers.append(str(val).strip().lower() if val is not None else "")

    # Validate required columns
    missing = [c for c in REQUIRED_COLS if c not in headers]
    if missing:
        raise ValueError(
            f"Missing required column(s) in '{SHEET_NAME}' sheet: {missing}\n"
            f"Found headers: {headers}"
        )

    col_idx = {h: i for i, h in enumerate(headers)}

    questions = []
    for row_num, row in enumerate(ws.iter_rows(min_row=2, values_only=True), start=2):
        # Skip rows with no question text
        question_text = row[col_idx["question"]]
        if not question_text or str(question_text).strip() == "":
            continue

        def get(col):
            v = row[col_idx[col]]
            return str(v).strip() if v is not None else ""

        # Parse correct answer (accept 0-3 or A-D)
        correct_raw = get("correct")
        if correct_raw.upper() in ("A", "B", "C", "D"):
            correct_idx = ord(correct_raw.upper()) - ord("A")
        else:
            try:
                correct_idx = int(float(correct_raw))
            except (ValueError, TypeError):
                print(
                    f"WARNING: Row {row_num} has invalid 'correct' value "
                    f"'{correct_raw}', defaulting to 0.",
                    file=sys.stderr,
                )
                correct_idx = 0

        if not 0 <= correct_idx <= 3:
            print(
                f"WARNING: Row {row_num} has out-of-range 'correct' value "
                f"{correct_idx}, clamping to 0.",
                file=sys.stderr,
            )
            correct_idx = max(0, min(3, correct_idx))

        # Build option strings with letter prefixes (A. … B. … etc.)
        letters = ["A", "B", "C", "D"]
        options = [f"{l}. {get(f'option_{l.lower()}')}" for l in letters]

        # Determine numeric id
        id_raw = get("id")
        try:
            q_id = int(float(id_raw)) if id_raw else len(questions) + 1
        except ValueError:
            q_id = len(questions) + 1

        questions.append({
            "id":          q_id,
            "unit":        get("unit"),
            "topic":       get("topic"),
            "question":    str(question_text).strip(),
            "options":     options,
            "correct":     correct_idx,
            "explanation": get("explanation"),
        })

    return questions


def questions_to_js(questions: list[dict]) -> str:
    """Serialise the questions list to the JS file format used by the quiz app."""
    lines = ["// Auto-generated by convert_questions.py — do not edit by hand.",
             "// Edit questions.xlsx and re-run the script (or push to trigger CI).",
             "// Last generated: " + datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M UTC"),
             "",
             "const QUESTIONS = ["]

    for i, q in enumerate(questions):
        comma = "," if i < len(questions) - 1 else ""
        opts_json = json.dumps(q["options"], ensure_ascii=False)
        expl_json = json.dumps(q["explanation"], ensure_ascii=False)
        unit_json = json.dumps(q["unit"], ensure_ascii=False)
        topic_json = json.dumps(q["topic"], ensure_ascii=False)
        qtext_json = json.dumps(q["question"], ensure_ascii=False)
        lines.append("  {")
        lines.append(f'    id: {q["id"]},')
        lines.append(f'    unit: {unit_json},')
        lines.append(f'    topic: {topic_json},')
        lines.append(f'    question: {qtext_json},')
        lines.append(f'    options: {opts_json},')
        lines.append(f'    correct: {q["correct"]},')
        lines.append(f'    explanation: {expl_json}')
        lines.append("  }" + comma)

    lines.append("];")
    return "\n".join(lines) + "\n"


def main():
    if not os.path.exists(EXCEL_FILE):
        print(f"ERROR: Excel file not found: {EXCEL_FILE}", file=sys.stderr)
        sys.exit(1)

    print(f"Reading questions from: {EXCEL_FILE}")
    questions = load_questions(EXCEL_FILE)
    print(f"Loaded {len(questions)} questions.")

    if not questions:
        print("ERROR: No questions found in the Excel file.", file=sys.stderr)
        sys.exit(1)

    js_content = questions_to_js(questions)

    os.makedirs(os.path.dirname(OUTPUT_FILE), exist_ok=True)
    with open(OUTPUT_FILE, "w", encoding="utf-8") as f:
        f.write(js_content)

    print(f"Written: {OUTPUT_FILE}")
    print(f"Done. {len(questions)} questions exported.")


if __name__ == "__main__":
    main()
