import json

questions = []
qid = 1

# ─────────────────────────────────────────────
# CHAPTER 1 — Risk Basics (30 questions)
# ─────────────────────────────────────────────
ch1 = [
  {"chapter":1,"chapterName":"Risk Basics","topic":"Basel Definition",
   "question":"According to the Basel Committee on Banking Supervision, operational risk is best defined as:",
   "options":["A. The risk of financial loss due to changes in market prices","B. The risk of loss resulting from inadequate or failed internal processes, people and systems or from external events","C. The risk that a counterparty will default on its obligations","D. The risk of insufficient liquidity to meet payment obligations"],
   "correct":1,"explanation":"The Basel Committee defines operational risk as 'the risk of loss resulting from inadequate or failed internal processes, people and systems or from external events', which includes legal risk but excludes strategic and reputational risk."},
  {"chapter":1,"chapterName":"Risk Basics","topic":"Basel Definition",
   "question":"Which of the following is explicitly excluded from the Basel Committee's definition of operational risk?",
   "options":["A. Legal risk","B. Technology risk","C. Strategic risk","D. Process risk"],
   "correct":2,"explanation":"The Basel definition explicitly excludes strategic risk and reputational risk, while including legal risk within operational risk."},
  {"chapter":1,"chapterName":"Risk Basics","topic":"Four Risk Categories",
   "question":"Which four categories of risk are most commonly referenced in banking and financial services risk frameworks?",
   "options":["A. Credit, Market, Liquidity, Operational","B. Credit, Interest Rate, Currency, Reputational","C. Market, Legal, Compliance, Strategic","D. Operational, Systemic, Concentration, Model"],
   "correct":0,"explanation":"The four primary risk categories in financial services are credit risk, market risk, liquidity risk, and operational risk. These form the cornerstone of Basel framework risk management."},
  {"chapter":1,"chapterName":"Risk Basics","topic":"Credit Risk Definition",
   "question":"Credit risk is most accurately described as:",
   "options":["A. The risk of loss from adverse changes in interest rates","B. The risk that a borrower or counterparty fails to meet its financial obligations","C. The risk of inadequate cash flow to fund operations","D. The risk of loss from employee misconduct"],
   "correct":1,"explanation":"Credit risk arises when a borrower or counterparty defaults or fails to meet its contractual financial obligations, resulting in a financial loss to the lender or investor."},
  {"chapter":1,"chapterName":"Risk Basics","topic":"Market Risk Definition",
   "question":"A bank's trading book is exposed to a fall in equity prices. This is an example of:",
   "options":["A. Credit risk","B. Liquidity risk","C. Market risk","D. Operational risk"],
   "correct":2,"explanation":"Market risk is the risk of losses from adverse movements in market prices including equity prices, interest rates, foreign exchange rates and commodity prices."},
  {"chapter":1,"chapterName":"Risk Basics","topic":"Liquidity Risk Definition",
   "question":"A firm is unable to sell a large block of bonds quickly without significantly reducing the price. This situation illustrates:",
   "options":["A. Funding liquidity risk","B. Asset liquidity risk","C. Credit risk","D. Settlement risk"],
   "correct":1,"explanation":"Asset liquidity risk (also called market liquidity risk) arises when a firm cannot liquidate a position quickly at fair market value. Funding liquidity risk relates to the inability to meet cash outflows."},
  {"chapter":1,"chapterName":"Risk Basics","topic":"Enterprise Risk Management",
   "question":"Enterprise Risk Management (ERM) differs from traditional risk management primarily because it:",
   "options":["A. Focuses solely on financial risks","B. Views risk management in silos by department","C. Takes a holistic, firm-wide view of all risks across the organisation","D. Only applies to listed companies"],
   "correct":2,"explanation":"ERM takes a holistic, integrated approach covering all risk types across the entire organisation, unlike traditional siloed risk management which treats each risk type independently."},
  {"chapter":1,"chapterName":"Risk Basics","topic":"Barings Bank",
   "question":"The Barings Bank collapse in 1995 was primarily caused by:",
   "options":["A. A cyberattack on its core banking system","B. Losses from rogue trading by Nick Leeson in Singapore amounting to approximately £827 million","C. Widespread mortgage defaults following a property crash","D. A failure of its settlement systems causing large fail losses"],
   "correct":1,"explanation":"Nick Leeson, a trader at Barings' Singapore office, accumulated unauthorised positions in futures contracts, hiding losses in error account 88888. Total losses reached approximately £827 million, causing Barings' collapse in 1995."},
  {"chapter":1,"chapterName":"Risk Basics","topic":"Barings Bank",
   "question":"Which internal control failure at Barings Bank allowed Nick Leeson to conceal his trading losses?",
   "options":["A. Inadequate IT systems","B. Leeson held both front office trading and back office settlement responsibilities simultaneously","C. Absence of a compliance department","D. Failure to implement Basel II capital requirements"],
   "correct":1,"explanation":"Leeson controlled both the trading desk and the back office settlement function, a fundamental breach of segregation of duties. This allowed him to create and conceal a fictitious error account (88888) to hide mounting losses."},
  {"chapter":1,"chapterName":"Risk Basics","topic":"Société Générale",
   "question":"The Société Générale rogue trading scandal of 2008 involved losses of approximately:",
   "options":["A. €1.2 billion","B. €4.9 billion","C. €7.3 billion","D. €2.1 billion"],
   "correct":1,"explanation":"Jérôme Kerviel, a trader at Société Générale, accumulated unauthorised directional positions in European equity index futures. When discovered and unwound in January 2008, the bank incurred losses of approximately €4.9 billion."},
  {"chapter":1,"chapterName":"Risk Basics","topic":"Société Générale",
   "question":"Jérôme Kerviel was able to conceal his positions at Société Générale primarily because:",
   "options":["A. He hacked into the bank's IT systems","B. He had previous back office experience and knowledge of the bank's control systems","C. Senior management were aware and approved the trades","D. Regulatory reporting requirements were not yet in force"],
   "correct":1,"explanation":"Kerviel used his knowledge of the bank's back office procedures and control systems, gained from prior experience in that role, to enter fictitious offsetting trades that masked his true exposure."},
  {"chapter":1,"chapterName":"Risk Basics","topic":"UBS Rogue Trading",
   "question":"In 2011, UBS disclosed a rogue trading loss of approximately $2.3 billion attributed to:",
   "options":["A. John Rusnak","B. Kweku Adoboli","C. Nick Leeson","D. Brian Hunter"],
   "correct":1,"explanation":"Kweku Adoboli, a trader in UBS's Exchange Traded Funds desk in London, accumulated unauthorised positions leading to losses of approximately $2.3 billion when discovered in September 2011."},
  {"chapter":1,"chapterName":"Risk Basics","topic":"LIBOR Scandal",
   "question":"The LIBOR scandal primarily involved:",
   "options":["A. Traders manipulating equity markets through spoofing","B. Banks submitting false rates to influence the London Interbank Offered Rate for profit or to appear financially stronger","C. Central banks coordinating to suppress short-term interest rates","D. Regulators deliberately setting LIBOR too low to stimulate lending"],
   "correct":1,"explanation":"The LIBOR scandal involved multiple banks submitting artificially high or low rate estimates to the LIBOR panel to benefit trading positions or to project financial health during the 2008 financial crisis."},
  {"chapter":1,"chapterName":"Risk Basics","topic":"LIBOR Scandal",
   "question":"The LIBOR manipulation scandal is primarily classified under which Basel loss event category?",
   "options":["A. External fraud","B. Damage to physical assets","C. Clients, products and business practices","D. Employment practices and workplace safety"],
   "correct":2,"explanation":"LIBOR manipulation falls under the 'Clients, products and business practices' Basel loss event category, as it involved improper conduct related to financial products and market practices."},
  {"chapter":1,"chapterName":"Risk Basics","topic":"Bangladesh Bank Heist",
   "question":"The 2016 Bangladesh Bank heist resulted in a loss of approximately $81 million. The attack was carried out by exploiting:",
   "options":["A. Physical break-in to the bank's vault","B. Fraudulent SWIFT payment messages to the Federal Reserve Bank of New York","C. Insider trading by senior bank executives","D. Manipulation of ATM software to dispense extra cash"],
   "correct":1,"explanation":"Hackers compromised Bangladesh Bank's SWIFT messaging credentials and submitted fraudulent transfer instructions to the Federal Reserve Bank of New York, resulting in $81 million being transferred to accounts in the Philippines before being detected."},
  {"chapter":1,"chapterName":"Risk Basics","topic":"Wells Fargo",
   "question":"The Wells Fargo fake accounts scandal (2016) was caused primarily by:",
   "options":["A. External hackers accessing customer accounts","B. A software failure in the bank's CRM system","C. Employees opening millions of unauthorised bank and credit accounts to meet aggressive sales targets","D. Regulatory failure to detect money laundering activities"],
   "correct":2,"explanation":"Driven by unrealistic sales incentives, Wells Fargo employees opened approximately 3.5 million unauthorised bank and credit card accounts in customers' names. This is an example of conduct risk and poor corporate culture."},
  {"chapter":1,"chapterName":"Risk Basics","topic":"Risk Management Objectives",
   "question":"The primary objective of risk management in a financial institution is to:",
   "options":["A. Eliminate all risks to protect shareholders","B. Identify, assess, monitor and control risks to an acceptable level aligned with the firm's risk appetite","C. Transfer all risks to third parties through insurance","D. Maximise returns by taking on the maximum possible risk"],
   "correct":1,"explanation":"Risk management aims to identify, assess, monitor and control risks within the organisation's risk appetite, not to eliminate all risk (which would prevent profit generation) or ignore risk."},
  {"chapter":1,"chapterName":"Risk Basics","topic":"Risk Management Objectives",
   "question":"Which statement best describes the concept of risk appetite?",
   "options":["A. The maximum possible loss a firm could suffer","B. The amount and type of risk a firm is willing to accept in pursuit of its business objectives","C. The minimum level of capital required by regulators","D. The level of risk that has been fully hedged or mitigated"],
   "correct":1,"explanation":"Risk appetite defines the amount and type of risk an organisation is willing to accept in pursuit of its strategic objectives, providing a framework for decision-making throughout the firm."},
  {"chapter":1,"chapterName":"Risk Basics","topic":"Risk Categories",
   "question":"A bank's foreign exchange trading position suffers a loss because a foreign currency depreciates. This is an example of:",
   "options":["A. Credit risk","B. Operational risk","C. Market risk","D. Concentration risk"],
   "correct":2,"explanation":"Foreign exchange rate movements are a form of market risk. The adverse movement in currency value causing trading losses is a classic market risk scenario."},
  {"chapter":1,"chapterName":"Risk Basics","topic":"Enterprise Risk Management",
   "question":"Which of the following best illustrates the interaction between operational risk and credit risk?",
   "options":["A. A rise in interest rates reducing bond portfolio values","B. A data entry error resulting in a loan being issued to the wrong customer","C. A competitor offering lower mortgage rates","D. A sovereign government defaulting on its bonds"],
   "correct":1,"explanation":"When an operational failure (data entry error) leads to a credit outcome (loan issued incorrectly), this illustrates how operational risk can trigger or amplify credit risk — a key ERM consideration."},
  {"chapter":1,"chapterName":"Risk Basics","topic":"Risk Basics",
   "question":"Which of the following is considered an example of operational risk rather than market risk?",
   "options":["A. A bond price falling due to rising interest rates","B. A currency depreciation causing trading losses","C. A trader manually booking a trade to the wrong account","D. A borrower defaulting on a corporate loan"],
   "correct":2,"explanation":"Manually booking a trade to the wrong account is an operational risk event (execution error/process failure). The other options represent market risk (A, B) and credit risk (D)."},
  {"chapter":1,"chapterName":"Risk Basics","topic":"Barings Bank",
   "question":"What was the name of the fictitious error account used by Nick Leeson at Barings Bank to conceal trading losses?",
   "options":["A. Account 99999","B. Account 12345","C. Account 88888","D. Account 00001"],
   "correct":2,"explanation":"Nick Leeson used account 88888, a fictitious client error account, to hide accumulating losses from his unauthorised trading positions in Nikkei futures contracts."},
  {"chapter":1,"chapterName":"Risk Basics","topic":"Risk Management Objectives",
   "question":"Which of the following most accurately describes the risk management process?",
   "options":["A. Risk identification → Risk assessment → Risk control → Risk monitoring","B. Risk monitoring → Risk control → Risk assessment → Risk identification","C. Risk control → Risk identification → Risk monitoring → Risk assessment","D. Risk assessment → Risk monitoring → Risk identification → Risk control"],
   "correct":0,"explanation":"The risk management process follows a logical sequence: first identify risks, then assess their likelihood and impact, implement controls to manage them, and monitor ongoing effectiveness."},
  {"chapter":1,"chapterName":"Risk Basics","topic":"LIBOR Scandal",
   "question":"The LIBOR scandal resulted in billions of dollars in fines. Which regulatory concept was most clearly violated?",
   "options":["A. Capital adequacy requirements","B. Market integrity and conduct standards","C. Anti-money laundering regulations","D. Data protection requirements"],
   "correct":1,"explanation":"The LIBOR manipulation scandal was fundamentally a breach of market integrity — banks were manipulating a key benchmark rate, violating conduct standards and undermining the integrity of financial markets."},
  {"chapter":1,"chapterName":"Risk Basics","topic":"Wells Fargo",
   "question":"The Wells Fargo scandal is most relevant to which operational risk concept?",
   "options":["A. Technology failure","B. Natural disaster impact","C. Conduct risk driven by poor corporate culture and incentive structures","D. Settlement and clearing failures"],
   "correct":2,"explanation":"Wells Fargo exemplifies conduct risk — employees behaved improperly due to a toxic sales culture with excessive targets and incentives. This is a human/people operational risk with regulatory and reputational consequences."},
  {"chapter":1,"chapterName":"Risk Basics","topic":"Four Risk Categories",
   "question":"Funding liquidity risk most closely relates to:",
   "options":["A. The risk that assets cannot be sold quickly","B. The risk that a firm cannot raise sufficient cash to meet its payment obligations as they fall due","C. The risk that market prices move adversely","D. The risk of unauthorised trading activity"],
   "correct":1,"explanation":"Funding liquidity risk is the risk that a firm cannot obtain sufficient funds (through asset sales, borrowing, or other means) to meet its payment obligations as they come due."},
  {"chapter":1,"chapterName":"Risk Basics","topic":"Enterprise Risk Management",
   "question":"In ERM, the concept of risk aggregation is important because:",
   "options":["A. It allows firms to ignore smaller individual risks","B. Individual risks may combine to create a larger overall risk exposure than if viewed in isolation","C. Aggregation eliminates the need for risk controls","D. It simplifies regulatory reporting requirements"],
   "correct":1,"explanation":"Risk aggregation recognises that individual risks across the firm may be correlated and when combined can present a materially larger exposure than if each risk were assessed independently."},
  {"chapter":1,"chapterName":"Risk Basics","topic":"Bangladesh Bank Heist",
   "question":"The Bangladesh Bank cyber heist is classified primarily under which operational risk loss event type?",
   "options":["A. Internal fraud","B. External fraud","C. Damage to physical assets","D. Employment practices and workplace safety"],
   "correct":1,"explanation":"The Bangladesh Bank heist was perpetrated by external hackers (not internal employees), making it an external fraud event — one of the Basel Committee's seven operational risk loss event categories."},
  {"chapter":1,"chapterName":"Risk Basics","topic":"Risk Management Objectives",
   "question":"A firm's board of directors approves a statement that the organisation will accept moderate credit risk but will not tolerate any regulatory breaches. This statement represents:",
   "options":["A. The firm's risk capacity","B. The firm's risk appetite statement","C. The firm's risk register","D. The firm's ICAAP document"],
   "correct":1,"explanation":"A risk appetite statement formally documents the types and levels of risk the organisation is willing to accept (or not accept) in pursuit of its objectives, approved at board level."},
  {"chapter":1,"chapterName":"Risk Basics","topic":"UBS Rogue Trading",
   "question":"The UBS rogue trading loss in 2011 is best categorised as which type of operational risk?",
   "options":["A. External fraud","B. Technology failure","C. Internal fraud — unauthorised trading","D. Clients, products and business practices"],
   "correct":2,"explanation":"Kweku Adoboli's unauthorised trading at UBS constitutes internal fraud (specifically, unauthorised trading activity by an employee), which is one of the Basel seven loss event categories."},
]
for q in ch1:
    q['id'] = qid
    qid += 1
questions.extend(ch1)

# ─────────────────────────────────────────────
# CHAPTER 2 — Other Major Risks (35 questions)
# ─────────────────────────────────────────────
ch2 = [
  {"chapter":2,"chapterName":"Other Major Risks","topic":"Sovereign Risk",
   "question":"Sovereign risk is best defined as:",
   "options":["A. The risk that a corporation defaults on its bonds","B. The risk that a national government is unable or unwilling to meet its debt obligations","C. The risk of loss from currency movements","D. The risk that a central bank raises interest rates unexpectedly"],
   "correct":1,"explanation":"Sovereign risk refers to the possibility that a national government will default on its debt or that political/economic conditions will impair the value of investments in that country."},
  {"chapter":2,"chapterName":"Other Major Risks","topic":"Russian Bond Default",
   "question":"Russia's default on its domestic government bonds in 1998 is a classic example of:",
   "options":["A. Market risk","B. Liquidity risk","C. Sovereign risk materialising","D. Operational risk"],
   "correct":2,"explanation":"Russia's 1998 default on GKO (rouble-denominated government bonds) is a textbook sovereign risk event, causing significant losses to foreign and domestic investors holding Russian government debt."},
  {"chapter":2,"chapterName":"Other Major Risks","topic":"Counterparty Risk",
   "question":"Counterparty risk in a derivatives transaction refers to:",
   "options":["A. The risk that market prices move against the position","B. The risk that the other party to the contract defaults before settlement","C. The risk that the contract terms are ambiguous","D. The risk that the regulator bans the instrument"],
   "correct":1,"explanation":"Counterparty risk (also called counterparty credit risk) is the risk that the counterparty in a financial transaction defaults on its obligations before final settlement, leaving the surviving party with a replacement cost exposure."},
  {"chapter":2,"chapterName":"Other Major Risks","topic":"DVP",
   "question":"Delivery Versus Payment (DVP) is a settlement mechanism designed to mitigate:",
   "options":["A. Market risk from price movements","B. Settlement risk by ensuring securities and cash are exchanged simultaneously","C. Credit risk from borrower defaults","D. Liquidity risk from funding gaps"],
   "correct":1,"explanation":"DVP ensures that the transfer of securities only occurs if and only if the corresponding cash payment is made simultaneously, eliminating principal risk (the risk of delivering securities without receiving payment)."},
  {"chapter":2,"chapterName":"Other Major Risks","topic":"Credit Ratings",
   "question":"According to Standard & Poor's rating scale, the lowest investment-grade credit rating is:",
   "options":["A. AA-","B. A-","C. BBB-","D. BB+"],
   "correct":2,"explanation":"BBB- (Standard & Poor's) / Baa3 (Moody's) is the lowest investment-grade rating. Bonds rated below BBB-/Baa3 are classified as sub-investment grade, high yield, or 'junk' bonds."},
  {"chapter":2,"chapterName":"Other Major Risks","topic":"Credit Ratings",
   "question":"Moody's highest credit rating, equivalent to S&P's AAA, is:",
   "options":["A. AA1","B. Aaa","C. A1","D. AA+"],
   "correct":1,"explanation":"Moody's highest rating is Aaa, equivalent to AAA on the Standard & Poor's and Fitch scales. This rating indicates the highest credit quality with minimal credit risk."},
  {"chapter":2,"chapterName":"Other Major Risks","topic":"Credit Ratings",
   "question":"A bond rated BB+ by Standard & Poor's is classified as:",
   "options":["A. Investment grade","B. Sub-investment grade (high yield)","C. Default","D. Not rated"],
   "correct":1,"explanation":"BB+ is one notch below BBB- (the lowest investment grade), placing it in the sub-investment grade or high-yield ('junk') category. These bonds carry higher credit risk and typically offer higher yields."},
  {"chapter":2,"chapterName":"Other Major Risks","topic":"VaR",
   "question":"Value at Risk (VaR) at a 99% confidence level over a one-day holding period means:",
   "options":["A. The portfolio will lose at least this amount 99% of the time","B. The maximum loss that will not be exceeded on 99 out of 100 trading days","C. The average loss expected on the worst 1% of trading days","D. The portfolio will gain this amount on 99% of trading days"],
   "correct":1,"explanation":"99% VaR represents the maximum loss that is not expected to be exceeded on 99 out of 100 trading days (or 1% of the time). It is a statistical measure of downside risk under normal market conditions."},
  {"chapter":2,"chapterName":"Other Major Risks","topic":"VaR",
   "question":"A key limitation of Value at Risk (VaR) as a risk measure is that:",
   "options":["A. It cannot be applied to equity portfolios","B. It says nothing about the magnitude of losses beyond the confidence threshold (tail risk)","C. It requires too many data inputs to be practical","D. It is banned under Basel III regulations"],
   "correct":1,"explanation":"VaR does not quantify how severe losses can be in the tail of the distribution beyond the confidence level. This limitation led to the development of Expected Shortfall (CVaR) as a complementary measure."},
  {"chapter":2,"chapterName":"Other Major Risks","topic":"Systemic Risk",
   "question":"Systemic risk in the context of financial markets refers to:",
   "options":["A. The risk that one company's IT system fails","B. The risk that the failure of one institution triggers a cascade of failures across the entire financial system","C. The risk of a natural disaster affecting financial infrastructure","D. The risk of a single large counterparty defaulting on a trade"],
   "correct":1,"explanation":"Systemic risk is the risk of collapse of an entire financial system or market, typically triggered by the failure of a major institution, creating contagion effects that spread to other interconnected institutions."},
  {"chapter":2,"chapterName":"Other Major Risks","topic":"Systemic Risk",
   "question":"The 2008 global financial crisis illustrated systemic risk because:",
   "options":["A. A single bank failed due to rogue trading","B. Troubles in the US sub-prime mortgage market spread to global financial institutions through securitisation and interconnectedness","C. A natural disaster destroyed major financial exchanges","D. A cyberattack compromised global payment systems"],
   "correct":1,"explanation":"The 2008 crisis showed how losses in US sub-prime mortgages, packaged into complex securities (CDOs, MBS), spread through the globally interconnected financial system, threatening multiple major institutions simultaneously."},
  {"chapter":2,"chapterName":"Other Major Risks","topic":"Funding vs Asset Liquidity",
   "question":"The distinction between funding liquidity risk and asset (market) liquidity risk is that:",
   "options":["A. They are the same concept described differently","B. Funding liquidity relates to cash availability; asset liquidity relates to the ease of selling assets at fair value","C. Funding liquidity is only a concern for banks; asset liquidity only affects investment funds","D. Asset liquidity risk only applies to illiquid asset classes like real estate"],
   "correct":1,"explanation":"Funding liquidity risk is about a firm's ability to meet cash obligations (liability side), whereas asset liquidity risk is about the ability to sell assets quickly without significant price impact (asset side)."},
  {"chapter":2,"chapterName":"Other Major Risks","topic":"Model Risk",
   "question":"Model risk arises when:",
   "options":["A. A firm fails to build any financial models","B. Errors or inappropriate assumptions in financial models lead to incorrect valuations or risk assessments","C. A regulator rejects a firm's internal model for capital calculation","D. A competitor uses a superior pricing model"],
   "correct":1,"explanation":"Model risk is the risk of adverse consequences from decisions based on incorrect or misused models. It includes errors in model design, incorrect assumptions, and inappropriate application of models to situations they were not designed for."},
  {"chapter":2,"chapterName":"Other Major Risks","topic":"Concentration Risk",
   "question":"A bank that has lent 40% of its loan book to a single industry sector is exposed to:",
   "options":["A. Sovereign risk","B. Concentration risk","C. Settlement risk","D. Funding liquidity risk"],
   "correct":1,"explanation":"Concentration risk arises when a large portion of a portfolio is exposed to a single borrower, industry, geography or asset class, meaning a downturn in that area could cause disproportionate losses."},
  {"chapter":2,"chapterName":"Other Major Risks","topic":"Reputational Risk",
   "question":"Reputational risk is best described as:",
   "options":["A. The risk of financial loss from interest rate movements","B. The risk of loss arising from negative public perception or damage to a firm's standing with stakeholders","C. The risk of regulatory fine for a single compliance breach","D. The risk that a firm's brand is not well known in new markets"],
   "correct":1,"explanation":"Reputational risk refers to the potential for negative publicity, public perception, or loss of trust to adversely affect a firm's revenues, client base, or ability to raise funding, even if no direct regulatory breach occurred."},
  {"chapter":2,"chapterName":"Other Major Risks","topic":"Legal Risk",
   "question":"Legal risk within the context of operational risk includes:",
   "options":["A. The risk that interest rates change adversely","B. The risk of loss arising from unenforceable contracts, litigation, or regulatory penalties","C. The risk of cyberattacks on legal databases","D. The risk that competitors file patents on key products"],
   "correct":1,"explanation":"Legal risk is a sub-category of operational risk in the Basel framework and includes exposure to fines, penalties, or losses from unenforceable contracts, litigation, and failure to comply with applicable laws."},
  {"chapter":2,"chapterName":"Other Major Risks","topic":"Settlement Risk",
   "question":"Settlement risk (also known as Herstatt risk) is the risk that:",
   "options":["A. A settlement system fails due to a technical error","B. One party to a transaction delivers on its obligation but the other party fails to deliver simultaneously","C. A central counterparty becomes insolvent","D. A settlement occurs outside normal market hours"],
   "correct":1,"explanation":"Settlement risk (named after Bankhaus Herstatt which failed in 1974) is the risk that one counterparty pays or delivers but the other side fails to complete its leg of the trade, resulting in a principal loss."},
  {"chapter":2,"chapterName":"Other Major Risks","topic":"Settlement Risk",
   "question":"The introduction of Continuous Linked Settlement (CLS) was designed primarily to reduce:",
   "options":["A. Credit risk in lending","B. Foreign exchange settlement risk by synchronising the two legs of FX transactions","C. Market risk in equity trading","D. Liquidity risk in money markets"],
   "correct":1,"explanation":"CLS Bank was established to mitigate FX settlement risk by settling both legs of a foreign exchange transaction simultaneously, dramatically reducing the principal risk exposure in FX markets."},
  {"chapter":2,"chapterName":"Other Major Risks","topic":"Capital Ratios",
   "question":"Under Basel III, the minimum Tier 1 capital ratio requirement for banks is:",
   "options":["A. 4%","B. 6%","C. 8%","D. 10%"],
   "correct":1,"explanation":"Basel III set the minimum Tier 1 capital ratio at 6% of risk-weighted assets. The total capital ratio (Tier 1 + Tier 2) minimum is 8%. Additional capital buffers apply on top of these minimums."},
  {"chapter":2,"chapterName":"Other Major Risks","topic":"Capital Ratios",
   "question":"The Total Capital Ratio under Basel III requires banks to hold a minimum of:",
   "options":["A. 4.5%","B. 6%","C. 8%","D. 10.5%"],
   "correct":2,"explanation":"The minimum Total Capital Ratio (Tier 1 plus Tier 2 capital) is 8% of risk-weighted assets under Basel III. The 4.5% is the Common Equity Tier 1 (CET1) minimum, and 10.5% includes the capital conservation buffer."},
  {"chapter":2,"chapterName":"Other Major Risks","topic":"Counterparty Risk",
   "question":"Pre-settlement risk in a derivatives contract is the risk that:",
   "options":["A. The contract has not yet been legally confirmed","B. The counterparty defaults before final settlement, leaving an exposure equal to the replacement cost","C. The settlement instruction is sent to the wrong counterparty","D. Market prices move before the trade is settled"],
   "correct":1,"explanation":"Pre-settlement risk (also called replacement cost risk) is the exposure arising if a counterparty defaults during the life of a derivatives contract, requiring the surviving party to replace the contract at current market prices."},
  {"chapter":2,"chapterName":"Other Major Risks","topic":"Sovereign Risk",
   "question":"When a sovereign government imposes capital controls restricting the ability to repatriate funds, this is known as:",
   "options":["A. Default risk","B. Transfer risk","C. Settlement risk","D. Model risk"],
   "correct":1,"explanation":"Transfer risk (a component of sovereign risk) is the risk that a government imposes restrictions preventing the transfer of funds out of the country, even if the obligor has the ability to pay in local currency."},
  {"chapter":2,"chapterName":"Other Major Risks","topic":"Credit Ratings",
   "question":"Which of the following rating actions would trigger forced selling by investment-grade-only institutional investors?",
   "options":["A. A rating downgrade from AAA to AA+","B. A rating downgrade from BBB- to BB+","C. A rating upgrade from BB+ to BBB-","D. A rating placed on negative watch by a rating agency"],
   "correct":1,"explanation":"A downgrade from BBB- to BB+ moves a bond from investment grade to sub-investment grade (junk). Many institutional investors (pension funds, insurance companies) have mandates that prohibit holding sub-investment-grade securities, forcing them to sell."},
  {"chapter":2,"chapterName":"Other Major Risks","topic":"VaR",
   "question":"Expected Shortfall (ES), also known as CVaR, improves on VaR because it:",
   "options":["A. Is easier to calculate and requires less data","B. Measures the average loss expected in the worst scenarios beyond the VaR confidence threshold","C. Is the only measure approved by the Basel Committee","D. Always produces a lower risk estimate than VaR"],
   "correct":1,"explanation":"Expected Shortfall measures the average loss in the worst (1 - confidence level) % of scenarios, providing information about the severity of tail losses that VaR ignores. Basel III's Fundamental Review of the Trading Book (FRTB) replaced VaR with ES."},
  {"chapter":2,"chapterName":"Other Major Risks","topic":"Concentration Risk",
   "question":"Concentration risk can arise in which of the following ways?",
   "options":["A. Only through single-name credit exposures","B. Through single-name, geographic, sector or instrument concentration in a portfolio","C. Only in trading book positions","D. Only through counterparty exposures in derivatives"],
   "correct":1,"explanation":"Concentration risk can arise in multiple dimensions: excessive exposure to a single counterparty, geographic region, industry sector, or financial instrument type. All these forms can create vulnerability to a specific shock."},
  {"chapter":2,"chapterName":"Other Major Risks","topic":"Model Risk",
   "question":"The collapse of Long-Term Capital Management (LTCM) in 1998 illustrates model risk because:",
   "options":["A. Their trading systems experienced a catastrophic IT failure","B. Their sophisticated mathematical models failed to account for extreme market conditions and liquidity constraints","C. Traders manipulated model inputs to conceal losses","D. Regulators rejected their internal model approval"],
   "correct":1,"explanation":"LTCM's models, built by Nobel Prize-winning economists, failed to account for the correlation breakdown and liquidity drying up in extreme market stress. This illustrates how model assumptions can fail catastrophically in tail events."},
  {"chapter":2,"chapterName":"Other Major Risks","topic":"Settlement Risk",
   "question":"Which settlement convention is currently standard for most equity markets globally?",
   "options":["A. T+0","B. T+1","C. T+2","D. T+3"],
   "correct":2,"explanation":"T+2 (trade date plus two business days) became the standard settlement convention for most equity markets. However, some markets including the US moved to T+1 in 2024."},
  {"chapter":2,"chapterName":"Other Major Risks","topic":"Reputational Risk",
   "question":"Reputational risk is particularly important in financial services because:",
   "options":["A. It is directly regulated by the FCA under specific capital requirements","B. Client trust is fundamental to a financial firm's ability to attract and retain business","C. It is the primary driver of credit rating decisions","D. It is the only risk that cannot be insured"],
   "correct":1,"explanation":"Financial services businesses are built on trust. Reputational damage can quickly lead to client attrition, funding difficulties, and regulatory scrutiny, making reputational risk management critically important despite being difficult to quantify."},
  {"chapter":2,"chapterName":"Other Major Risks","topic":"Legal Risk",
   "question":"A bank enters into a derivatives contract governed by a foreign jurisdiction, which later renders the contract void under local law. This is an example of:",
   "options":["A. Settlement risk","B. Legal risk","C. Market risk","D. Counterparty risk"],
   "correct":1,"explanation":"The risk that a contract is unenforceable due to foreign jurisdiction law is a classic legal risk scenario. This type of risk highlights the importance of proper documentation and legal due diligence in cross-border transactions."},
  {"chapter":2,"chapterName":"Other Major Risks","topic":"Capital Ratios",
   "question":"Tier 1 capital primarily consists of:",
   "options":["A. Subordinated debt and hybrid instruments","B. Common Equity Tier 1 (CET1) including ordinary shares and retained earnings","C. Loan loss provisions and general reserves","D. Short-term bank borrowings"],
   "correct":1,"explanation":"Tier 1 capital represents the highest quality regulatory capital, primarily comprising Common Equity Tier 1 (CET1) which includes common shares, share premium, and retained earnings — the most loss-absorbing form of capital."},
  {"chapter":2,"chapterName":"Other Major Risks","topic":"Sovereign Risk",
   "question":"Which of the following best illustrates the difference between inability and unwillingness to pay sovereign debt?",
   "options":["A. A country with foreign currency reserves runs out of dollars — inability; a country with reserves chooses to default for political reasons — unwillingness","B. Inability occurs only in emerging markets; unwillingness only in developed markets","C. Inability is a legal concept; unwillingness is an economic concept","D. There is no meaningful difference between the two"],
   "correct":0,"explanation":"Sovereign risk encompasses both inability to pay (due to insufficient foreign reserves or economic collapse) and unwillingness to pay (a political decision to default despite having the financial capacity to service debt)."},
  {"chapter":2,"chapterName":"Other Major Risks","topic":"DVP",
   "question":"What is Free versus Payment (FvP) in securities settlement?",
   "options":["A. Securities are delivered simultaneously with payment — the preferred risk-free method","B. Securities are transferred without a corresponding cash payment, creating settlement risk","C. A payment is made before securities are delivered","D. Securities are settled via a central counterparty at no cost"],
   "correct":1,"explanation":"Free versus Payment (FvP) is when securities are transferred without a simultaneous cash leg. Unlike DVP, this creates settlement risk for the delivering party who may not receive payment after delivering the securities."},
  {"chapter":2,"chapterName":"Other Major Risks","topic":"Systemic Risk",
   "question":"The concept of 'too big to fail' relates most directly to which type of risk?",
   "options":["A. Concentration risk in a single firm","B. Systemic risk — the failure of a major institution could destabilise the entire financial system","C. Sovereign risk from government guaranteed institutions","D. Settlement risk from large interbank exposures"],
   "correct":1,"explanation":"'Too big to fail' institutions pose systemic risk because their failure could trigger a cascade of failures across the financial system. This concept drove post-2008 regulatory reforms including resolution planning and additional capital buffers for G-SIBs."},
  {"chapter":2,"chapterName":"Other Major Risks","topic":"Counterparty Risk",
   "question":"Central clearing through a CCP (Central Counterparty Clearing House) reduces counterparty risk in OTC derivatives by:",
   "options":["A. Guaranteeing all trades against market price movements","B. Becoming the buyer to every seller and seller to every buyer, backed by margin and default fund resources","C. Eliminating the need for derivatives documentation","D. Requiring all trades to be settled on the same day"],
   "correct":1,"explanation":"A CCP interposes itself as the counterparty to both sides of every cleared trade ('novation'). This mutualises and manages counterparty risk through margin requirements and mutualised default funds."},
  {"chapter":2,"chapterName":"Other Major Risks","topic":"Model Risk",
   "question":"Which of the following is a primary safeguard against model risk?",
   "options":["A. Using only externally developed models","B. Independent model validation and regular back-testing against actual outcomes","C. Restricting model use to specific geographic markets","D. Using models developed exclusively by front office traders"],
   "correct":1,"explanation":"Independent model validation (by a team separate from model developers) and ongoing back-testing against real outcomes are the primary controls against model risk, ensuring models perform as expected and assumptions remain valid."},
]
for q in ch2:
    q['id'] = qid
    qid += 1
questions.extend(ch2)

print(f"After Ch1+Ch2: {len(questions)} questions")

with open('/home/runner/work/CISIPRAC/CISIPRAC/write_questions_part1.py', 'w') as f:
    f.write("# Part 1 written")
print("Done")
